version: '3.7'

services:
    # development related
    test-sqlite:
        environment: 
            - PYTHONDONTWRITEBYTECODE=1
        build:
            dockerfile: docker/app/Dockerfile
            context: .
        entrypoint: pytest
        volumes: 
            - ./ThoughtsBackend:/opt/code
